# Generated by Django 5.0 on 2024-01-11 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_foo_bar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bar',
            options={'verbose_name': 'Bar', 'verbose_name_plural': 'Bars'},
        ),
        migrations.AlterField(
            model_name='bar',
            name='django_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
