# Generated by Django 5.0 on 2024-01-11 09:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_alter_bar_options_alter_bar_django_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
