# Generated by Django 5.0 on 2024-01-12 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_barowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='barowner',
            field=models.ForeignKey(default='2b2b29a9-3a32-431d-96a1-df09bf1870a5', on_delete=django.db.models.deletion.CASCADE, to='snippets.barowner'),
            preserve_default=False,
        ),
    ]
